wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815158" -q -O html/Normal_011.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815159" -q -O html/Normal_010.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815160" -q -O html/Normal_009.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815161" -q -O html/Normal_003.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815162" -q -O html/Normal_006.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815163" -q -O html/BRCA2_005.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815164" -q -O html/BRCA1_002.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815165" -q -O html/BRCA2_006.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815166" -q -O html/BRCA2_007.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815167" -q -O html/BRCA2_004.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815168" -q -O html/Normal_002.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815169" -q -O html/Normal_001.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815170" -q -O html/BRCA1_001.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815171" -q -O html/BRCA1_003.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815172" -q -O html/BRCAX_013.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815173" -q -O html/BRCAX_009.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815174" -q -O html/BRCAX_016.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815175" -q -O html/BRCAX_019.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815176" -q -O html/BRCAX_017.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815177" -q -O html/BRCAX_018.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815178" -q -O html/BRCAX_020.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815179" -q -O html/BRCAX_014.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815180" -q -O html/BRCAX_010.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815181" -q -O html/BRCAX_012.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815182" -q -O html/BRCAX_011.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815183" -q -O html/Normal_005.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815184" -q -O html/Normal_004.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815185" -q -O html/Human_Cells.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815186" -q -O html/BRCA2_008.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815187" -q -O html/BRCAX_022.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815188" -q -O html/BRCAX_021.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815189" -q -O html/Normal_012.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815190" -q -O html/Normal_014.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815191" -q -O html/Normal_008.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815192" -q -O html/Normal_015.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815193" -q -O html/Normal_013.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815194" -q -O html/Normal_007.html
wget "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSM815195" -q -O html/BRCAX_015.html
