if [ $# -lt 1 ]
then
    echo 'Usage: samfile'
    exit
fi

lnk=(GCTGTTAAGGACCGTACATCCGCCTTGGCCGTCCTTAACAGC
GCTGTTAAGGACCGTACATCCGCCTTGGCCGTGACATTGACC
GGTCAATGTCACCGTACATCCGCCTTGGCCGTCCTTAACAGC
GGTCAATGTCACCGTACATCCGCCTTGGCCGTGACATTGACC
GCTGTTAAGGACGGCCAAGGCGGATGTACGGTCCTTAACAGC
GGTCAATGTCACGGCCAAGGCGGATGTACGGTCCTTAACAGC
GCTGTTAAGGACGGCCAAGGCGGATGTACGGTGACATTGACC
GGTCAATGTCACGGCCAAGGCGGATGTACGGTGACATTGACC
)

for x in ${lnk[*]}
do
    for ((i=0;i<=2;i++))
    do
	y=$x.*NM:i:$i
	echo $y
	grep $y $1 |wc -l
    done
done
